version: "3.8"

services:
  # Fire Snake 301 Application
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fire-snake-301-app
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_SERVER_ENABLE_STATIC_SERVING=true
      - STREAMLIT_SERVER_RUN_ON_SAVE=false
    volumes:
      - ./outputs:/app/outputs
      - ./.streamlit:/app/.streamlit
    networks:
      - fire-snake-network
    expose:
      - "8501"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: fire-snake-301-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - streamlit
    networks:
      - fire-snake-network

networks:
  fire-snake-network:
    driver: bridge
    name: fire-snake-network